### PR TITLE
Upgrade `jetty-client` to 9.2.22.v20170606

### PR DESCRIPTION
**Pull request by tvhung83**
- Upgrade `jetty-client` to `9.2.22.v20170606` in attempt to include fix of bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=441756

### CODE REVIEW

**Comment by dmikurube** [comment]
@tvhung83 lgtm2, and agreed with Muga's comment. :)

btw, can you wait for merging till tomorrow? I was going to release v0.7.39 soon. I'd like to split the releases to avoid confusion.

**Comment by tvhung83** [comment]
Ah, thank you @muga and @dmikurube , i will split the change of `msgpack` test dependency.
@dmikurube yes, I will wait :)

**Comment by tvhung83** [comment]
hi @dmikurube , should i merge and release this now?

**Comment by dmikurube** [comment]
@tvhung83 Ah, sorry I forgot to notify you. 0.7.39 has been released, and there're no blockers as far as I know. @muga looks fine with this. Please go ahead. (Possibly nice to have his last check.)

**Comment by tvhung83** [comment]
hi @muga , I'll go ahead to merge and verify this, please feel free to add comments. I'll address any issue in another PR.

**Pull request merged**
