### PR TITLE
Catch and retry for most SocketException while requesting to TD API.

### PR DESCRIPTION
**Pull request by dmikurube**
@muga Can you have a look?

### CODE REVIEW

**Comment by dmikurube** [comment]
@muga Thanks. Having one nit fix (`TDClientSocketException`'s comment), and then going to merge.

Then, I'll try releasing thew next version.

**Comment by muga** [comment]
@dmikurube LGTM. nice catch.

**Comment by muga** [comment]
Since the CI failed, I rebuilt it. If the CI will fail again, we need to check it.

**Comment by dmikurube** [comment]
CI passed. :)

@muga Merging this...

**Pull request merged**
